version: '2'
services:
  ugc-app:
    image: ugc
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://ugc-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=ugc
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9090:9090
  ugc-mongodb:
    extends:
      file: mongodb.yml
      service: ugc-mongodb
